
title: Clément Vandoolaeghe Resume
url: 'https://cvando.github.io/online-cv'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Clément Vandoolaeghe
tagline: DevOps cloud manager
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: Clement.vandoolaeghe@gmail.com 
phone: 0669364960
website: noopspool.com
linkedin: clement-vandoolaeghe
github: Redacted


# Tracker
analytics: 111
#Update all the sections by editing the files inside _includes folder.
